### ISSUE TITLE
Chunk issue

### ISSUE THREAD

**Issue by MFDGaming** [JSPrismarine/JSPrismarine#465]
When I startup then server and reaches to the loading/generating message the os just locks up for 5-8 seconds. When I join the server the chunks get loaded/generated up to A point and then the generator/loader seems unresponsive and some time when I try to load those chunks the os locks up for 2-3 seconds. I am running node js 14.16.1 on debian Gnu/Linux x86_64.

**Comment by filiphsandstrom** [comment]
This will be fixed once we implement a real World provider (that being Anvil, a more stable LevelDB or whatever). I'll probably look into writing a bedrock-targeted anvil provider as my next task (provided something else doesn't pop up beforehand).

@HerryYT This should probably target `v0.1.0` instead of `v0.2.0` since we don't want to have to deal with world conversions between versions just yet right?
